ALTER TABLE empresa_sync_states
    ADD COLUMN IF NOT EXISTS nfse_habilitada BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS ult_nsu_nfse VARCHAR(255) NOT NULL DEFAULT '0',
    ADD COLUMN IF NOT EXISTS ultima_sync_nfse TIMESTAMP,
    ADD COLUMN IF NOT EXISTS nfse_blocked_until TIMESTAMP;
